'use client'

import { useState } from 'react'
import { Activity, Check, ChevronDown, Clipboard, Paperclip, PanelRight, RefreshCw, Send, ThumbsDown, ThumbsUp, Upload, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Sidebar, Topbar } from '@/components/enterprise/workspace'
import { ConversationSidebar } from './conversation-sidebar'
import { SourceInspector } from './source-inspector'
import { assistantConversations, assistantSources, executionActivity, type AssistantSource } from '@/lib/mock-data'

function Citation({ label, onClick }: { label: string; onClick: () => void }) { return <button className="citation" onClick={onClick} aria-label={`Open source ${label}`}>{label}</button> }
function ActivitySteps() { const [open, setOpen] = useState(false); return <div className="activity-surface"><button className="flex w-full items-center gap-3 text-left" onClick={() => setOpen(!open)} aria-expanded={open}><span className="activity-surface-icon"><Activity /></span><span className="min-w-0 flex-1"><span className="block text-xs font-medium">Operational execution</span><span className="mt-1 block text-[11px] text-muted-foreground">5 stages · 1.8s · grounded-v2</span></span><ChevronDown className={`size-4 text-muted-foreground transition-transform ${open ? 'rotate-180' : ''}`} /></button>{open && <div className="execution-steps">{executionActivity.map((step) => <div className="execution-step" key={step.label}><span className="execution-check"><Check /></span><span><strong>{step.label}</strong><small>{step.detail}</small></span></div>)}</div>}</div> }
function ChatMessage({ onCitation }: { onCitation: (id: string) => void }) { return <div className="chat-thread"><div className="message-user"><div className="avatar avatar-small">MC</div><div><p className="message-label">You · 11:48 AM</p><p className="message-user-text">What is the enterprise refund policy for customers?</p></div></div><div className="message-assistant"><div className="assistant-mark">N</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="message-label">Enterprise AI Assistant</p><span className="status-dot" /></div><div className="assistant-answer mt-3"><p>Enterprise customers may request a full refund within <strong>30 days of initial activation</strong> when the service has not materially met the contracted requirements <Citation label="[1]" onClick={() => onCitation('source-1')} />.</p><p>Requests submitted after 30 days require Finance approval. Refunds and credits must also align with the customer&apos;s order form and applicable service-level commitments <Citation label="[2]" onClick={() => onCitation('source-2')} />.</p><ul><li>Submit the request through the account owner.</li><li>Include the order form and reason for the request.</li><li>Escalate exceptions to Finance for review.</li></ul></div><div className="message-actions"><button aria-label="Copy answer"><Clipboard />Copy</button><button aria-label="Regenerate answer"><RefreshCw />Regenerate</button><span className="flex-1" /><button aria-label="Helpful"><ThumbsUp /></button><button aria-label="Not helpful"><ThumbsDown /></button></div></div></div><ActivitySteps /></div> }
function Composer({ onSend }: { onSend: (value: string) => void }) { const [value, setValue] = useState(''); const [attached, setAttached] = useState(false); const submit = () => { if (value.trim()) { onSend(value); setValue('') } }; return <div className="composer-wrap"><div className="flex flex-wrap gap-2 pb-3"><button className="suggested-prompt" onClick={() => setValue('What is the enterprise refund policy?')}>What is the enterprise refund policy?</button><button className="suggested-prompt" onClick={() => setValue('What approval steps are required before a production deployment?')}>Production approval steps</button><button className="suggested-prompt" onClick={() => setValue('Check ticket INC-1042 and summarize the next action.')}>Summarize INC-1042</button></div><div className="composer"><textarea value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing && event.keyCode !== 229) { event.preventDefault(); submit() } }} placeholder="Ask a grounded question about your workspace..." rows={2} aria-label="Ask a grounded question" /><div className="flex items-center justify-between gap-3 border-t border-border/70 pt-3"><div className="flex items-center gap-2"><button className={`prompt-action ${attached ? 'text-primary' : ''}`} onClick={() => setAttached(!attached)} aria-label="Attach a document"><Paperclip /><span className="hidden sm:inline">Attach</span></button>{attached && <span className="attachment-chip"><Upload />policy.pdf <X /></span>}<span className="hidden text-[10px] text-muted-foreground md:inline">PDF, Markdown, or text</span></div><div className="flex items-center gap-2"><button className="mode-selector">Grounded <ChevronDown /></button><Button size="sm" onClick={submit} aria-label="Send message"><Send data-icon="inline-start" />Send</Button></div></div></div><p className="mt-2 text-center text-[10px] text-muted-foreground">Press <kbd>Enter</kbd> to send · <kbd>Shift Enter</kbd> for a new line · Answers cite connected sources</p></div> }

export function AssistantWorkspace() { const [sidebarOpen, setSidebarOpen] = useState(false); const [commandOpen, setCommandOpen] = useState(false); const [activeId, setActiveId] = useState('refund-policy'); const [inspectorOpen, setInspectorOpen] = useState(true); const [selectedSource, setSelectedSource] = useState<AssistantSource>(assistantSources[0]); const [sent, setSent] = useState(''); const selectSource = (id: string) => { const source = assistantSources.find((item) => item.id === id); if (source) { setSelectedSource(source); setInspectorOpen(true) } }; return <div className="workspace-shell"><Sidebar active="Conversations" setActive={() => undefined} open={sidebarOpen} onClose={() => setSidebarOpen(false)} /><div className="workspace-main"><Topbar section="Assistant" onMenu={() => setSidebarOpen(true)} onSearch={() => setCommandOpen(!commandOpen)} /><main className="assistant-content"><div className="assistant-heading"><div><p className="eyebrow">Enterprise AI assistant</p><h1 className="page-title">Ask your workspace</h1><p className="mt-1 max-w-2xl text-xs leading-5 text-muted-foreground">Grounded answers across connected knowledge.</p></div><Button variant="outline" size="sm" onClick={() => setInspectorOpen(!inspectorOpen)}><PanelRight data-icon="inline-start" />{inspectorOpen ? 'Hide sources' : 'Show sources'}</Button></div><div className={`assistant-grid ${inspectorOpen ? '' : 'assistant-grid-collapsed'}`}><ConversationSidebar conversations={assistantConversations} activeId={activeId} onSelect={setActiveId} onNew={() => setActiveId('refund-policy')} /><section className="chat-main" aria-label="Assistant conversation"><div className="chat-status"><span className="status-dot" />Grounded mode <span>·</span><span className="text-muted-foreground">Connected knowledge is current</span></div><div className="chat-scroll"><div className="empty-thread-note"><span className="status-dot" />Conversation grounded in 2 verified sources</div><ChatMessage onCitation={selectSource} />{sent && <div className="message-user"><div className="avatar avatar-small">MC</div><div><p className="message-label">You · just now</p><p className="message-user-text">{sent}</p></div></div>}</div><Composer onSend={setSent} /></section>{inspectorOpen && <SourceInspector source={selectedSource} sources={assistantSources} onSelect={selectSource} onClose={() => setInspectorOpen(false)} />}</div></main></div>{commandOpen && <button className="command-overlay" aria-label="Close command menu" onClick={() => setCommandOpen(false)}><span className="sr-only">Command menu placeholder</span></button>}</div> }
